services:
  survey-tool:
    image: survey-tool:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      # Port definition, needs to be same as PORT env variable
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - survey-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - survey-net

volumes:
  prometheus_data: {}
    
networks:
  survey-net:
    driver: bridge