apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: st
  name: survey-tool-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: survey-tool-svc
            port:
              number: 9090