apiVersion: 1

datasources:
  - name: survey-tool-loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    version: 1
    jsonData:
      maxLines: 1000