apiVersion: v1
kind: Service
metadata:
  namespace: st
  name: survey-tool-svc
spec:
  type: NodePort
  selector:
    app: survey-tool
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9000
      nodePort: 30090